# Generated by Django 5.1.2 on 2024-10-30 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('banner_color', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('album_art', models.URLField(default='http://example.com/placeholder.jpg')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='poll.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('album_art', models.URLField(default='http://example.com/placeholder.jpg')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topsongs', to='poll.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_ip', models.CharField(max_length=39)),
                ('vote_text', models.CharField(blank=True, max_length=200, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_votes', to='poll.artist')),
            ],
            options={
                'unique_together': {('artist', 'voter_ip')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='poll.vote')),
            ],
        ),
    ]
