# Generated by Django 5.1.2 on 2024-10-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_vote_voter_ip'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter_ip',
        ),
    ]
