# Generated by Django 5.1.2 on 2025-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_artist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
