# This is a basic workflow to help you get started with Actions

name: Run Python Script

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
  client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          pip install Django>=3.2,<4.0 requests>=2.26.0 beautifulsoup4>=4.10.0 spotipy>=2.19.0 numpy>=1.21.0 Pillow>=8.4.0 scikit-learn>=0.24.2 more-itertools>=8.10.0

      - name: Run Script
        run: |
          python Goat/poll/data.py
