name: Run Python Script

on:
  workflow_dispatch:

env:
  client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
  client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
